azure:
  free_disk_space: true
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_ppc64le: github_actions
  linux_aarch64: github_actions
  linux_64: github_actions
  osx_64: github_actions
  win_64: github_actions
github_actions:
  free_disk_space: true
test: native_and_emulated
skip_render:
  - README.md
  - LICENSE.txt
  - .github/workflows/automerge.yml
  - .github/workflows/webservices.yml
